SELECT * FROM searchengine.urldata;CREATE DATABASE `searchengine` /*!40100 DEFAULT CHARACTER SET utf8 */;
CREATE TABLE `keydata` (
  `KID` int(11) NOT NULL,
  `UID` int(11) NOT NULL,
  `Frequency` int(11) NOT NULL,
  `KD_ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`KID`,`UID`),
  UNIQUE KEY `KD_ID_UNIQUE` (`KD_ID`),
  KEY `URLID_idx` (`UID`),
  CONSTRAINT `KeyID` FOREIGN KEY (`KID`) REFERENCES `keywords` (`Key_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `URLID` FOREIGN KEY (`UID`) REFERENCES `urldata` (`URL_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1133 DEFAULT CHARSET=utf8;

CREATE TABLE `keywords` (
  `Key_ID` int(11) NOT NULL AUTO_INCREMENT,
  `KeyWord` varchar(50) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`Key_ID`),
  UNIQUE KEY `KeyWord_UNIQUE` (`KeyWord`)
) ENGINE=InnoDB AUTO_INCREMENT=1089 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `ranking` (
  `KDID` int(11) NOT NULL,
  `Position` int(11) NOT NULL,
  `Tag` int(11) NOT NULL,
  PRIMARY KEY (`KDID`,`Position`),
  CONSTRAINT `KDID` FOREIGN KEY (`KDID`) REFERENCES `keydata` (`KD_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `restricted` (
  `RURL_id` int(11) NOT NULL AUTO_INCREMENT,
  `rURL` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`RURL_id`),
  UNIQUE KEY `rURL_UNIQUE` (`rURL`(255))
) ENGINE=InnoDB AUTO_INCREMENT=1027 DEFAULT CHARSET=utf8;

CREATE TABLE `urldata` (
  `URL_ID` int(11) NOT NULL AUTO_INCREMENT,
  `URL` varchar(1000) CHARACTER SET utf8 NOT NULL,
  `Visited` char(1) CHARACTER SET utf8 NOT NULL DEFAULT 'F',
  `Indexed` char(1) CHARACTER SET utf8 NOT NULL DEFAULT 'F',
  `Downloaded` char(1) CHARACTER SET utf8 NOT NULL DEFAULT 'F',
  `Priority` char(1) CHARACTER SET utf8 NOT NULL DEFAULT 'L',
  `Popularity` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`URL_ID`),
  UNIQUE KEY `URL_UNIQUE` (`URL`(255))
) ENGINE=InnoDB AUTO_INCREMENT=27026 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
